'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),W=960,H=540,FLOOR=372,keys=new Set(),pressed=new Set();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defs=[{name:'へへへへへ',en:'HEHEHEHEHE',hp:1000,speed:3.6,color:'#ff4655',file:'hehe.png',moves:[['含み笑い掌','U / ↓↘→ + J','素早い短距離突進',90,12,5,22,112],['笑天アッパー','I / →↓↘ + J','対空。空振りの隙大',125,8,9,36,80],['忍び笑い','O / ↓↙← + L','低い姿勢の足払い',80,16,7,21,122],['大爆笑・百裂掌','P / ゲージ100','近距離の連続掌打',300,13,14,40,160]]},{name:'壇 美鶴',en:'DAN MITSURU',hp:1100,speed:2.8,color:'#419dff',file:'dan.png',moves:[['決裁掌','U / ↓↘→ + J','遅めの気弾で間合いを支配',100,21,4,27,95],['白銀昇天','I / →↓↘ + J','強力な対空。ガード後は危険',150,11,10,40,98],['威圧の踏込','O / ↓↙← + L','長いリーチの突進蹴り',130,22,7,30,155],['最終決裁・鉄槌','P / ゲージ100','踏み込んで放つ重い鉄槌',330,20,12,45,185]]}];
let selected=0,mode='normal',state='menu',paused=false,round=1,wins=[0,0],fighters=[],timer=3600,intro=0,endDelay=0,freeze=0,flash=0,shake=0,particles=[],projectiles=[],floaters=[],tick=0,aiClock=0,sound=true,audio,ready=false,acc=0,last=0,frames=[],stage=new Image(),inputHistory=[],throwSequence=null;
function sfx(type,f,m){
 if(!sound)return;const bank=window.FightAudio;if(!bank)return;
 if(type==='hit'){const name=m?.kind==='super'||m?.kind==='special'?'special-hit':m?.key==='l'?'kick':m?.key==='k'?(f?.id===1?'punch-heavy2':'punch-heavy1'):'punch-light';bank.play(name,{volume:m?.kind==='super'?.9:.65,rate:f?.id===1?.94:1.04,duck:m?.kind==='super'});}
 else if(type==='guard')bank.play(['impact1','impact2','impact3'][tick%3],{volume:.3,rate:1.15,lowpass:1500});
 else if(type==='super')bank.play('super-start',{volume:.75,duck:true});
 else if(type==='fight'||type==='ko')bank.play(type,{volume:.9,duck:true});
 else if(type==='throw')bank.play('throw',{volume:.7});
 else if(type==='slam'){bank.play('fall',{volume:.85});bank.play('impact6',{volume:.4,rate:.84});}
 else if(type==='land')bank.play('fall',{volume:.14,rate:1.25,maxDuration:.3,lowpass:1200});
 else if(type==='select')bank.play('impact2',{volume:.12,rate:1.5,maxDuration:.12,lowpass:2400});
}
function fighter(id,x,side){return {id,x,y:0,vy:0,face:side,hp:defs[id].hp,meter:0,move:null,t:0,stun:0,guard:false,crouch:false,walk:false,hit:false,combo:0,comboTimer:0,invuln:0,knock:0,pose:0,history:[],held:false,throwing:false,down:0,downDir:1,forcedPose:null}}
function newRound(){window.FightAudio?.stop();throwSequence=null;fighters=[fighter(selected,260,1),fighter(1-selected,700,-1)];timer=3600;intro=110;endDelay=0;particles=[];projectiles=[];floaters=[];freeze=0;paused=false;inputHistory=[];if(mode==='training'){fighters.forEach(f=>f.meter=100);timer=3600}state='fight';$('status').textContent=mode==='training'?'TRAINING':'ROUND '+round;$('hint').textContent='逆方向でガード · 必殺技 U / I / O · 超必殺 P'}
function start(){if(!ready)return;window.FightAudio?.unlock();mode=$('difficulty').value;wins=[0,0];round=1;newRound();$('menu').classList.add('hidden');$('result').classList.add('hidden');$('pause').classList.remove('hidden');window.FightAudio?.setScene(true)}
function menu(){window.FightAudio?.setScene(false);throwSequence=null;state='menu';paused=false;keys.clear();pressed.clear();$('menu').classList.remove('hidden');$('result').classList.add('hidden');$('pause').classList.add('hidden');$('status').textContent='SELECT YOUR FIGHTER';$('hint').textContent='キャラクターを選んで対戦開始'}
function attackData(f,key){let power=f.id===1;let m={key,start:5,active:3,recovery:11,damage:power?48:40,range:power?82:72,pose:4,kind:'normal',level:'mid',push:9};if(key==='k')Object.assign(m,{start:power?13:10,active:5,recovery:20,damage:power?95:78,range:power?112:99,push:18});if(key==='l')Object.assign(m,{start:power?15:12,active:5,recovery:22,damage:power?100:85,range:power?136:119,pose:5,push:22});if(f.crouch&&key==='l'){m.level='low';m.pose=9;m.range+=10}if(f.y>0){m.level='high';m.range+=12;m.pose=5}if(key==='h')Object.assign(m,{start:7,active:3,recovery:32,damage:130,range:60,kind:'throw',pose:7,push:50});let n=['u','i','o','p'].indexOf(key);if(n>=0){const d=defs[f.id].moves[n];Object.assign(m,{name:d[0],damage:d[3],start:d[4],active:d[5],recovery:d[6],range:d[7],kind:n===3?'super':'special',pose:[7,6,f.id===0?9:5,7][n],push:n===3?65:25,level:n===2&&f.id===0?'low':'mid'});if(n===1)m.anti=true;if(n===0&&f.id===1)m.projectile=true;if(n===0&&f.id===0||n===2&&f.id===1||n===3)m.dash=true}return m}
function attack(f,key){if(f.held||f.throwing||f.down||f.stun||f.hp<=0||intro||endDelay||f.y>0&&['u','i','o','p','h'].includes(key))return false;let m=attackData(f,key);if(f.move){let cancel=f.hit&&f.move.kind==='normal'&&(m.kind==='special'||m.kind==='super'||f.move.key==='j'&&['k','l'].includes(key));if(!cancel)return false}if(m.kind==='super'){if(f.meter<100){if(f===fighters[0])floaters.push({x:f.x,y:240,text:'NEED 100%',color:'#eab37c',life:35});return false}f.meter-=100;flash=15;freeze=12;sfx('super');floaters.push({x:W/2,y:175,text:m.name,color:defs[f.id].color,life:80})}if(m.kind==='special')floaters.push({x:f.x,y:215,text:m.name,color:defs[f.id].color,life:36});f.move=m;f.t=0;f.hit=false;f.guard=false;if(m.anti)f.invuln=5;return true}
function burst(x,y,color){for(let n=0;n<16;n++){let a=n*Math.PI/8;particles.push({x,y,vx:Math.cos(a)*(2+Math.random()*7),vy:Math.sin(a)*(2+Math.random()*7),life:14+Math.random()*12,color})}}
function hit(att,def,m){if(def.invuln>0||def.hp<=0||def.held||def.throwing||def.down)return false;if(m.kind==='throw')return beginThrow(att,def,m);let blocked=m.kind!=='throw'&&def.guard&&def.y===0&&(m.level!=='low'||def.crouch)&&(m.level!=='high'||!def.crouch);let counter=!!def.move&&!blocked;let damage=Math.round(m.damage*Math.max(.4,1-att.combo*.15)*(counter?1.1:1));if(blocked){damage=['special','super'].includes(m.kind)?Math.min(def.hp-1,Math.ceil(m.damage*.08)):0;def.stun=11+(m.kind==='super'?8:0);def.knock=att.face*3;sfx('guard');burst(def.x-def.face*20,FLOOR-def.y-110,'#9ad5ec');floaters.push({x:def.x,y:290,text:'GUARD',color:'#9ad5ec',life:20})}else{def.stun=m.kind==='super'?40:m.kind==='throw'?32:21;def.knock=att.face*(m.push/5);def.move=null;def.combo=0;att.combo++;att.comboTimer=70;def.pose=10;sfx('hit',att,m);burst(def.x,FLOOR-def.y-100,defs[att.id].color);if(counter)floaters.push({x:def.x,y:260,text:'COUNTER',color:'#eeb46f',life:35});if(m.anti&&def.y>0){def.vy=6;def.y+=10}if(m.kind==='super'){shake=18;flash=8}else shake=5}
 def.hp=Math.max(0,def.hp-damage);att.meter=clamp(att.meter+(blocked?4:9),0,100);def.meter=clamp(def.meter+(blocked?5:7),0,100);att.hit=true;freeze=blocked?3:m.kind==='super'?14:6;return true}
function movement(f,dir,jump,crouch){if(f.held||f.throwing||f.down||f.move||f.stun)return;f.crouch=crouch&&f.y===0;f.walk=false;f.guard=dir===-f.face&&f.y===0;if(jump&&f.y===0&&!f.crouch){f.vy=11.5;f.y=1}if(dir&&!f.crouch){f.x+=dir*defs[f.id].speed*(f.guard?.7:1);f.walk=true}}
function playerInput(f){let dx=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);movement(f,dx,pressed.has('ArrowUp'),keys.has('ArrowDown'));let dir=keys.has('ArrowDown')?(dx===f.face?'df':dx===-f.face?'db':'d'):dx===f.face?'f':dx===-f.face?'b':'n';if(!inputHistory.length||inputHistory.at(-1).d!==dir)inputHistory.push({d:dir,t:tick});inputHistory=inputHistory.filter(x=>tick-x.t<25);for(let k of ['j','k','l','u','i','o','h','p'])if(pressed.has(k)){let seq=inputHistory.map(x=>x.d).join(',');if(k==='j'&&/f,.*d,.*df/.test(seq))k='i';else if(k==='j'&&/d,.*df,.*f/.test(seq))k='u';else if(k==='l'&&/d,.*db,.*b/.test(seq))k='o';attack(f,k)}}
function ai(f,p){if(mode==='training'){f.guard=false;return}let dist=Math.abs(f.x-p.x),level=mode==='easy'?0:mode==='hard'?2:1;aiClock--;let danger=p.move&&dist<180;let dir=dist>145?f.face:dist<68?-f.face:0;let guarding=danger&&Math.sin(tick*.08+f.id)>[.75,.1,-.4][level];movement(f,guarding?-f.face:dir,false,guarding&&p.move.level==='low');if(aiClock<=0&&!f.stun&&!f.move){aiClock=[35,23,15][level]+Math.floor(Math.random()*20);let r=Math.random();if(p.y>35&&dist<135)attack(f,'i');else if(dist<175&&f.meter>=100&&r<.25)attack(f,'p');else if(dist<60&&p.guard&&r<.6)attack(f,'h');else if(dist<145)attack(f,r<.4?'j':r<.7?'l':r<.86?'k':'u');else if(dist<280&&r<.45)attack(f,f.id===1?'u':'o');else if(r<.16)movement(f,f.face,true,false)}}
function updateFighter(f,other){if(f.held||f.throwing)return;if(f.down>0){f.down--;if(!f.down){f.invuln=12;f.face=other.x>=f.x?1:-1}return}f.invuln=Math.max(0,f.invuln-1);if(f.comboTimer>0)f.comboTimer--;else f.combo=0;if(f.stun>0)f.stun--;f.x+=f.knock;f.knock*=.76;if(Math.abs(f.knock)<.1)f.knock=0;if(f.y>0||f.vy){f.y+=f.vy;f.vy-=.58;if(f.y<=0){f.y=0;f.vy=0;sfx('land')}}
 if(!f.move&&!f.stun)f.face=other.x>=f.x?1:-1;
 if(f.move){let m=f.move;f.t++;if(m.dash&&f.t>=m.start-5&&f.t<m.start+m.active)f.x+=f.face*(m.kind==='super'?4.5:3.5);if(m.projectile&&f.t===m.start){projectiles.push({owner:f,x:f.x+f.face*60,y:91,vx:f.face*5.6,life:120,m})}if(!m.projectile&&!f.hit&&f.t>=m.start&&f.t<m.start+m.active){let dist=(other.x-f.x)*f.face;let vertical=Math.abs(other.y-f.y);if(dist>=-15&&dist<m.range&&vertical<(m.anti?190:90))hit(f,other,m)}if(f.held||f.throwing)return;if(f.t>=m.start+m.active+m.recovery){f.move=null;f.hit=false}}
 f.x=clamp(f.x,55,905)}
function beginThrow(att,def,m){
 if(throwSequence||att.y>0||att.held||att.down||def.y>0||def.stun>0||def.invuln>0||def.down||def.held||def.throwing)return false;
 const distance=(def.x-att.x)*att.face;if(distance<0||distance>m.range)return false;
 const dir=att.face;
 // Leave room for both bodies even with the defender against a corner.
 const anchor=clamp(att.x,dir===1?70:210,dir===1?750:890);
 throwSequence={att,def,dir,anchor,t:0,m,landed:false,damage:m.damage};
 att.x=anchor;att.move=null;att.throwing=true;att.hit=true;att.knock=0;att.forcedPose=8;
 def.x=anchor+dir*30;def.move=null;def.held=true;def.guard=false;def.crouch=false;def.knock=0;def.vy=0;def.combo=0;
 sfx('throw');floaters.push({x:anchor,y:170,text:'THROW',color:defs[att.id].color,life:35});return true;
}
function throwVisual(q){
 const t=q.t,dir=q.dir,x=q.anchor;
 if(t<10){const p=t/10;return {x:x+dir*(35-15*p),cy:FLOOR-112-25*p,angle:-dir*.2*p};}
 if(t<23){const p=(t-10)/13;return {x:x+dir*(20+28*p),cy:FLOOR-137-75*Math.sin(p*Math.PI/2),angle:-dir*(.2+p*2.45)};}
 if(t<34){const p=(t-23)/11;return {x:x+dir*(48+87*p),cy:FLOOR-212+178*p*p,angle:-dir*(2.65-p*(2.65-Math.PI/2))};}
 const p=Math.min(1,(t-34)/12);return {x:x+dir*135,cy:FLOOR-34-18*Math.sin(p*Math.PI),angle:-dir*Math.PI/2};
}
function updateThrow(){
 const q=throwSequence;if(!q)return;q.t++;const {att,def,dir}=q;att.forcedPose=q.t<10?8:q.t<23?6:9;
 const v=throwVisual(q);def.x=v.x;def.y=Math.max(0,FLOOR-v.cy-100);
 if(q.t===34&&!q.landed){q.landed=true;def.hp=Math.max(0,def.hp-q.damage);att.meter=clamp(att.meter+12,0,100);def.meter=clamp(def.meter+10,0,100);att.combo=1;att.comboTimer=65;shake=17;freeze=8;sfx('slam');burst(v.x,FLOOR-10,'#cfbca0');}
 if(q.t>=46){def.held=false;def.y=0;def.vy=0;def.down=42;def.downDir=dir;def.stun=0;def.invuln=0;att.throwing=false;att.forcedPose=null;att.stun=14;att.hit=false;throwSequence=null;}
}
function update(){tick++;if(state!=='fight'||paused){pressed.clear();return}if(freeze>0){freeze--;return}if(intro>0){intro--;if(intro===40)sfx('fight');pressed.clear();return}if(endDelay>0){endDelay--;if(!endDelay){if(Math.max(...wins)>=2){state='result';let idx=wins[0]>wins[1]?0:1;$('winner').textContent=defs[fighters[idx].id].name+' WIN';$('score').textContent=wins[0]+' — '+wins[1]+(idx===0?' / YOU WIN':' / TRY AGAIN');$('result').classList.remove('hidden');$('pause').classList.add('hidden')}else{round++;newRound()}}return}
 const [a,b]=fighters;if(throwSequence)updateThrow();else{playerInput(a);ai(b,a);updateFighter(a,b);updateFighter(b,a);}if(!throwSequence&&!a.down&&!b.down&&Math.abs(a.x-b.x)<52&&Math.abs(a.y-b.y)<70){let mid=(a.x+b.x)/2;let sign=a.x<=b.x?-1:1;a.x=clamp(mid+sign*26,55,905);b.x=clamp(mid-sign*26,55,905)}
 projectiles=projectiles.filter(p=>{p.x+=p.vx;p.life--;let other=p.owner===a?b:a;if(Math.abs(p.x-other.x)<32&&Math.abs(p.y-(other.y+90))<70){if(hit(p.owner,other,p.m))return false}return p.life>0&&p.x>-30&&p.x<W+30});
 if(mode==='training'){timer=3600;a.meter=b.meter=100;if(tick%180===0&&!throwSequence){a.hp=defs[a.id].hp;b.hp=defs[b.id].hp}}else{timer=Math.max(0,timer-1);if(!throwSequence&&(a.hp<=0||b.hp<=0||timer<=0)){let ratioA=a.hp/defs[a.id].hp,ratioB=b.hp/defs[b.id].hp;if(ratioA===ratioB){wins[0]++;wins[1]++}else wins[ratioA>ratioB?0:1]++;endDelay=150;if(a.hp<=0||b.hp<=0)sfx('ko')}}pressed.clear()}
function text(t,x,y,size=20,color='#fff',align='left'){ctx.font=`900 ${size}px "Teko", "Dela Gothic One", sans-serif`;ctx.textAlign=align;ctx.lineWidth=4;ctx.strokeStyle='#081211';ctx.strokeText(t,x,y);ctx.fillStyle=color;ctx.fillText(t,x,y)}
function drawSprite(f,menuPose=false){if(f.held)return;if(f.down>10||f.hp<=0){drawDown(f);return}let pose=0;if(f.forcedPose!==null)pose=f.forcedPose;else if(f.down>0)pose=9;else if(menuPose)pose=0;else if(f.hp<=0)pose=10;else if(endDelay>0&&f.hp>0)pose=11;else if(f.stun)pose=f.guard?8:10;else if(f.move){pose=f.t<f.move.start?0:f.move.pose;if(f.move.kind==='super'&&f.t>=f.move.start&&f.t<f.move.start+f.move.active)pose=f.id===0?(Math.floor(f.t/3)%2?4:7):6;if(f.t>f.move.start+f.move.active+Math.floor(f.move.recovery/2))pose=0}else if(f.y>0)pose=5;else if(f.crouch)pose=9;else if(f.guard)pose=8;else if(f.walk)pose=2+Math.floor(tick/7)%2;else pose=Math.floor(tick/19)%2;let asset=frames[f.id]?.[pose];if(!asset)return;ctx.save();ctx.translate(Math.round(f.x),Math.round(FLOOR-f.y));ctx.scale(f.face,1);if(f.hp<=0){ctx.rotate(-Math.PI/2);ctx.translate(80,-40)}ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,2,58,9,0,0,Math.PI*2);ctx.fill();let bob=(!f.move&&!f.stun&&!f.walk&&f.y===0)?Math.floor(Math.sin(tick*.07)*1.2):0;ctx.drawImage(asset.img,asset.sx,asset.sy,asset.sw,asset.sh,Math.round(-asset.dw/2),Math.round(-asset.dh+bob),asset.dw,asset.dh);ctx.restore()}
function drawBody(f,pose,x,cy,angle){const asset=frames[f.id]?.[pose];if(!asset)return;ctx.save();ctx.translate(Math.round(x),Math.round(cy));ctx.rotate(angle);ctx.scale(f.face,1);ctx.drawImage(asset.img,asset.sx,asset.sy,asset.sw,asset.sh,-asset.dw/2,-asset.dh/2,asset.dw,asset.dh);ctx.restore();}
function drawDown(f){ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(f.x,FLOOR,100,10,0,0,Math.PI*2);ctx.fill();drawBody(f,10,f.x,FLOOR-34,-(f.downDir||f.face)*Math.PI/2);}
function drawThrown(){if(!throwSequence)return;const q=throwSequence,v=throwVisual(q);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(v.x,FLOOR,50,8,0,0,Math.PI*2);ctx.fill();drawBody(q.def,10,v.x,v.cy,v.angle);}
function bar(f,x,y,w,right){
 const ratio=f.hp/defs[f.id].hp;
 ctx.save();ctx.translate(x,y);ctx.transform(1,0,right?.18:-.18,1,0,0);
 ctx.fillStyle='#050815';ctx.fillRect(-5,-5,w+10,32);ctx.fillStyle='#a7b5cc';ctx.fillRect(-2,-2,w+4,26);ctx.fillStyle='#411427';ctx.fillRect(0,0,w,22);
 let gradient=ctx.createLinearGradient(0,0,0,22);gradient.addColorStop(0,'#fff4a2');gradient.addColorStop(.45,'#ffcf4c');gradient.addColorStop(1,ratio<.25?'#c52c32':'#e07821');ctx.fillStyle=gradient;ctx.fillRect(right?w-w*ratio:0,0,w*ratio,22);ctx.fillStyle='#ffffff70';ctx.fillRect(right?w-w*ratio:0,2,w*ratio,3);ctx.restore();
 text(defs[f.id].name,right?x+w:x,y-17,25,'#fff',right?'right':'left');text((right?'CPU':'1P')+' / '+defs[f.id].en,right?x+w:x,y+44,16,defs[f.id].color,right?'right':'left');
 for(let i=0;i<2;i++){let px=right?x+w-i*21:x+i*21;ctx.save();ctx.translate(px,y+59);ctx.rotate(Math.PI/4);ctx.fillStyle=wins[right?1:0]>i?'#ffd459':'#26324c';ctx.fillRect(-5,-5,10,10);ctx.restore()}
}
function meter(f,x,right){let w=270;ctx.fillStyle='#071311e8';ctx.fillRect(x,492,w,17);ctx.fillStyle=defs[f.id].color;ctx.fillRect(right?x+w-w*f.meter/100:x,492,w*f.meter/100,17);text(f.meter>=100?'SUPER READY':`POWER ${Math.floor(f.meter)}%`,right?x+w:x,530,15,defs[f.id].color,right?'right':'left');for(let i=1;i<4;i++){ctx.fillStyle='#101711';ctx.fillRect(x+i*w/4,492,3,17)}}
function render(){ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,W,H);ctx.save();if(shake>0){ctx.translate(Math.random()*shake-shake/2,Math.random()*shake-shake/2);shake*=.85;if(shake<.5)shake=0}if(stage.complete&&stage.naturalWidth)ctx.drawImage(stage,0,0,W,H);else{ctx.fillStyle='#152425';ctx.fillRect(0,0,W,H)}ctx.fillStyle='#07141238';ctx.fillRect(0,0,W,H);if(state==='menu'){
 const red=ctx.createLinearGradient(0,0,470,540);red.addColorStop(0,'#640f26e8');red.addColorStop(1,'#270c29b0');ctx.fillStyle=red;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(580,0);ctx.lineTo(405,540);ctx.lineTo(0,540);ctx.fill();
 const blue=ctx.createLinearGradient(500,0,960,540);blue.addColorStop(0,'#071b41cc');blue.addColorStop(1,'#123b84e8');ctx.fillStyle=blue;ctx.beginPath();ctx.moveTo(580,0);ctx.lineTo(960,0);ctx.lineTo(960,540);ctx.lineTo(405,540);ctx.fill();
 ctx.strokeStyle='#c5d4ff55';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(580,0);ctx.lineTo(405,540);ctx.stroke();
 for(let id=0;id<2;id++){const f=frames[id]?.[0];if(!f)continue;ctx.save();ctx.globalAlpha=selected===id?1:.7;ctx.translate(id?747:215,505);ctx.scale(id?-1:1,1);const scale=1.55;ctx.drawImage(f.img,f.sx,f.sy,f.sw,f.sh,-f.dw*scale/2,-f.dh*scale,f.dw*scale,f.dh*scale);ctx.restore()}
} else if(fighters.length){for(let f of fighters)drawSprite(f);drawThrown();for(let p of projectiles){ctx.fillStyle='#efc786';ctx.shadowBlur=16;ctx.shadowColor='#ffb345';ctx.fillRect(p.x-22,FLOOR-p.y-14,44,28);ctx.fillStyle='#fff3c7';ctx.fillRect(p.x-12,FLOOR-p.y-7,26,14);ctx.shadowBlur=0}for(let p of particles){if(!paused){p.x+=p.vx;p.y+=p.vy;p.vy+=.15;p.life--}ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.life>10?5:3,3)}particles=particles.filter(p=>p.life>0)}ctx.restore();if(state!=='menu'&&fighters.length){bar(fighters[0],35,63,360,false);bar(fighters[1],565,63,360,true);text(mode==='training'?'∞':String(Math.ceil(timer/60)).padStart(2,'0'),480,78,56,'#ffd05a','center');text('ROUND '+round,480,99,12,'#b3c2b5','center');meter(fighters[0],35,false);meter(fighters[1],655,true);fighters.forEach((f,i)=>{if(f.combo>1&&f.comboTimer)text(f.combo+' HIT',i?890:70,190,30,defs[f.id].color,i?'right':'left')});for(let f of floaters){text(f.text,f.x,f.y,23,f.color,'center');if(!paused){f.y-=.3;f.life--}}floaters=floaters.filter(f=>f.life>0);if(intro>0){text(intro>40?'ROUND '+round:'FIGHT',480,280,intro>40?60:90,intro>40?'#e9f0ff':'#ffcc4a','center')}if(endDelay>0)text(timer<=0?'TIME UP':fighters.some(f=>f.hp<=0)?'K.O.':'DRAW',480,270,100,'#f0e7c8','center');if(paused){ctx.fillStyle='#06100ccc';ctx.fillRect(0,0,W,H);text('PAUSED',480,255,64,'#ffcc4a','center');text('Ⅱ / Esc で再開',480,300,20,'#ddd','center')}}if(flash>0){ctx.fillStyle=`rgba(217,245,199,${flash/35})`;ctx.fillRect(0,0,W,H);flash--}}
function loop(now){window.FightAudio?.setScene(state==='fight'&&!paused);if(!last)last=now;acc+=Math.min(now-last,100);last=now;while(acc>=1000/60){update();acc-=1000/60}render();requestAnimationFrame(loop)}
function normalize(k){return {a:'ArrowLeft',d:'ArrowRight',w:'ArrowUp',s:'ArrowDown'}[k.toLowerCase()]||(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(k)?k:k.toLowerCase())}
function keyDown(k){if(!keys.has(k))pressed.add(k);keys.add(k)}
window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;let k=normalize(e.key);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','j','k','l','u','i','o','h','p',' '].includes(k)){e.preventDefault();keyDown(k)}if(e.key==='Escape'&&state==='fight'&&!e.repeat){paused=!paused;if(!paused)window.FightAudio?.unlock();keys.clear()}if(e.key==='Enter'&&state==='menu')start()});window.addEventListener('keyup',e=>keys.delete(normalize(e.key)));window.addEventListener('blur',()=>{keys.clear();pressed.clear();if(state==='fight')paused=true});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='fight'){paused=true;keys.clear()}});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keyDown(b.dataset.key);b.classList.add('pressed')});for(let ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>{keys.delete(b.dataset.key);b.classList.remove('pressed')})});
document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{window.FightAudio?.unlock();sfx('select');selected=+b.dataset.char;document.querySelectorAll('[data-char]').forEach(x=>x.classList.toggle('selected',x===b))});$('start').onclick=start;$('rematch').onclick=start;$('choose').onclick=menu;$('reset').onclick=menu;$('pause').onclick=()=>{paused=!paused;if(!paused)window.FightAudio?.unlock();keys.clear()};$('sound').onclick=()=>{sound=!sound;$('sound').textContent='SOUND '+(sound?'ON':'OFF');window.FightAudio?.setEnabled(sound)};$('help').onclick=()=>{if(state==='fight')paused=true;$('guide').showModal()};$('close').onclick=()=>$('guide').close();
$('movelist').innerHTML=defs.map(d=>`<h3>${d.name} <small>体力 ${d.hp}</small></h3><table><thead><tr><th>技</th><th>入力</th><th>威力</th><th>発生 / 持続 / 硬直</th></tr></thead><tbody>${d.moves.map(m=>`<tr><td>${m[0]}<br><small>${m[2]}</small></td><td>${m[1]}</td><td>${m[3]}</td><td>${m[4]} / ${m[5]} / ${m[6]} F</td></tr>`).join('')}</tbody></table>`).join('');
const spriteBoxes={
'hehe.png':[[42,27,267,401],[348,34,592,401],[658,32,921,401],[979,32,1238,401],[32,453,334,787],[362,435,656,787],[652,436,889,787],[900,473,1244,782],[29,847,292,1209],[365,938,574,1206],[673,870,902,1207],[997,795,1243,1209]],
'dan.png':[[24,16,286,395],[343,15,604,394],[667,14,930,394],[965,15,1243,395],[8,459,303,796],[315,437,655,798],[645,415,899,796],[920,477,1251,796],[26,858,315,1216],[353,952,596,1212],[681,869,932,1215],[1004,804,1250,1216]]};
async function loadSprites(file){
 const im=new Image();im.src='assets/'+file;await im.decode();
 const temp=document.createElement('canvas');temp.width=im.width;temp.height=im.height;
 const g=temp.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);
 const pixels=g.getImageData(0,0,im.width,im.height),data=pixels.data,n=im.width*im.height;
 // Runtime matte: flood only neutral backdrop connected to outer edges, preserving enclosed highlights.
 const visited=new Uint8Array(n),queue=new Int32Array(n);let head=0,tail=0;
 function enqueue(i){if(i<0||i>=n||visited[i])return;visited[i]=1;let k=i*4,r=data[k],gr=data[k+1],b=data[k+2];if(data[k+3]<100||Math.min(r,gr,b)>145&&Math.max(r,gr,b)-Math.min(r,gr,b)<12){queue[tail++]=i;data[k+3]=0}}
 for(let x=0;x<im.width;x++){enqueue(x);enqueue(n-im.width+x)}for(let y=0;y<im.height;y++){enqueue(y*im.width);enqueue(y*im.width+im.width-1)}
 enqueue(1058*im.width+500);if(file==='dan.png')enqueue(190*im.width+1046);while(head<tail){let i=queue[head++];if(i%im.width)enqueue(i-1);if(i%im.width<im.width-1)enqueue(i+1);enqueue(i-im.width);enqueue(i+im.width)}
 g.putImageData(pixels,0,0);const boxes=spriteBoxes[file],scale=225/(boxes[0][3]-boxes[0][1]);
 return boxes.map(([x,y,x2,y2])=>({img:temp,sx:x,sy:y,sw:x2-x,sh:y2-y,dw:Math.round((x2-x)*scale),dh:Math.round((y2-y)*scale)}))
}
async function init(){try{stage.src='assets/stage.webp';frames=await Promise.all(defs.map(d=>loadSprites(d.file)));await stage.decode();ready=true;$('loading').textContent='READY — キャラクターを選んで開始';$('start').disabled=false}catch(e){$('loading').textContent='素材を読み込めませんでした。ページを再読み込みしてください。';$('start').disabled=true;console.error(e)}}
let musicOn=true;$('music').onclick=()=>{musicOn=!musicOn;$('music').textContent='BGM '+(musicOn?'ON':'OFF');window.FightAudio?.setMusic(musicOn)};window.FightAudio?.load();$('start').disabled=true;init();requestAnimationFrame(loop);
window.FightEngine={defs,fighter,attackData,attack,hit,updateFighter,beginThrow,updateThrow,throwVisual,getThrow:()=>throwSequence,getState:()=>({state,fighters,wins,timer}),start};
