const $=id=>document.getElementById(id),canvas=$('avatar'),ctx=canvas.getContext('2d',{alpha:true}),audio=$('audio'),video=$('video');
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),outputMode=new URLSearchParams(location.search).get('output')==='1';
const defaults={character:'mau',costume:'track',framing:'full',expression:'auto',sensitivity:1.5,threshold:.02,motion:true,accessory:true,petPosition:'right',background:'transparent',zoom:1};
let config={...defaults};try{Object.assign(config,JSON.parse(localStorage.getItem('mautuber-v3')||'{}'))}catch{}
const query=new URLSearchParams(location.search);for(const k in defaults)if(query.has(k)){const v=query.get(k);config[k]=typeof defaults[k]==='boolean'?v==='true':typeof defaults[k]==='number'?Number(v):v}
let model,atlas,pet,loadToken=0,ac,analyser,samples,micSource,micStream,fileSource,fileUrl,camStream,tracker,trackerPromise,cameraStarting=false,face=null,lastDetect=0,lastVideoTime=-1;
let smooth={mouth:0,blink:0,smile:0,roll:0,x:0},demoUntil=0,nextBlink=performance.now()+2500,blinkUntil=0,last=performance.now();
const settingIds=Object.keys(defaults);
function status(id,text,error=false){$(id).textContent=text;$(id).classList.toggle('error',error)}
function loadImage(src){return new Promise((ok,no)=>{const im=new Image;im.onload=()=>ok(im);im.onerror=()=>no(Error('画像を読み込めません: '+src));im.src=src})}
function validModel(m){if(m?.format!=='mautuber-sprite-v1'||m.columns!==3||m.rows!==2||!m.atlas||!m.frames)throw Error('モデル設定が正しくありません');return m}
async function loadModel(){const token=++loadToken,key=config.character+'-'+config.costume;status('modelName','モデル読み込み中…');try{const r=await fetch('./models/'+key+'.json');if(!r.ok)throw Error('モデル設定を読み込めません');const m=validModel(await r.json()),im=await loadImage('./models/'+m.atlas);if(token!==loadToken)return;model=m;atlas=im;status('modelName',m.name+' / '+m.costumeName);$('loadError').hidden=true}catch(e){if(token===loadToken){status('loadError',e.message,true);$('loadError').hidden=false}}}
loadModel();loadImage('./models/muri.webp').then(v=>pet=v).catch(()=>{status('loadError','ムリねこを読み込めませんでした。',true);$('loadError').hidden=false});
function sync(){for(const id of settingIds){const e=$(id);if(!e)continue;if(e.type==='checkbox')e.checked=!!config[id];else e.value=config[id]}$('sensitivityValue').value=Number(config.sensitivity).toFixed(1)+'×';$('thresholdValue').value=Math.round(config.threshold*100)+'%';const stage=$('stage');stage.classList.toggle('checker',config.background==='transparent');stage.style.backgroundColor={green:'#00ff00',dark:'#20222c',white:'#fff'}[config.background]||''}
function save(){localStorage.setItem('mautuber-v3',JSON.stringify(config))}
for(const id of settingIds){const e=$(id);if(!e)continue;e.addEventListener('input',()=>{config[id]=e.type==='checkbox'?e.checked:e.type==='range'?Number(e.value):e.value;sync();save();if(id==='character'||id==='costume')loadModel()})}sync();
async function ensureAudio(){if(!ac){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('このブラウザは音声解析に対応していません。');ac=new AC;analyser=ac.createAnalyser();analyser.fftSize=1024;samples=new Float32Array(analyser.fftSize)}if(ac.state!=='running')await ac.resume()}
function stopMic(){if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;if(micSource)micSource.disconnect();micSource=null;$('mic').textContent=$('outputMic').textContent='マイクをオン';$('mic').classList.remove('active')}
async function toggleMic(){if(micStream){stopMic();status('audioStatus','マイクを停止しました。');return}try{audio.pause();await ensureAudio();status('audioStatus','マイクの使用を許可してください。');const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});micStream=s;micSource=ac.createMediaStreamSource(s);micSource.connect(analyser);s.getTracks().forEach(t=>t.onended=stopMic);$('mic').textContent=$('outputMic').textContent='マイクをオフ';$('mic').classList.add('active');status('audioStatus','マイク入力中。声に合わせて口が動きます。')}catch(e){stopMic();status('audioStatus',deviceError(e,'マイク'),true)}}
function deviceError(e,name){if(e?.name==='NotAllowedError')return name+'が許可されていません。ブラウザのサイト設定を確認してください。';if(e?.name==='NotFoundError')return name+'が見つかりません。';return e?.message||name+'を開始できませんでした。'}
$('mic').onclick=$('outputMic').onclick=toggleMic;
function tab(name){stopMic();audio.pause();for(const n of ['mic','file']){$(n+'Tab').setAttribute('aria-selected',n===name);$(n+'Panel').hidden=n!==name}status('audioStatus','入力を選んで開始してください。')}
$('micTab').onclick=()=>tab('mic');$('fileTab').onclick=()=>tab('file');
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl=URL.createObjectURL(f);audio.src=fileUrl;$('filename').textContent=f.name;try{await ensureAudio();if(!fileSource){fileSource=ac.createMediaElementSource(audio);fileSource.connect(analyser);fileSource.connect(ac.destination)}status('audioStatus','再生すると音声に合わせて動きます。')}catch(e){status('audioStatus',e.message,true)}};
audio.onplay=async()=>{stopMic();try{await ensureAudio();if(!fileSource){fileSource=ac.createMediaElementSource(audio);fileSource.connect(analyser);fileSource.connect(ac.destination)}status('audioStatus','録音音声に連動中。')}catch(e){audio.pause();status('audioStatus',e.message,true)}};
async function getTracker(){if(tracker)return tracker;if(!trackerPromise)trackerPromise=(async()=>{const {FaceLandmarker,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs');const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');tracker=await FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true});return tracker})().catch(e=>{trackerPromise=null;throw e});return trackerPromise}
function stopCamera(){if(camStream)camStream.getTracks().forEach(t=>t.stop());camStream=null;video.pause();video.srcObject=null;face=null;cameraStarting=false;$('camera').textContent=$('outputCamera').textContent='カメラをオン';$('calibrate').disabled=true}
async function toggleCamera(){if(camStream||cameraStarting){stopCamera();status('cameraStatus','カメラを停止しました。');return}cameraStarting=true;$('camera').textContent='読み込み中止';try{status('cameraStatus','顔認識データを読み込み中…');await getTracker();if(!cameraStarting)return;const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640}},audio:false});camStream=s;video.srcObject=s;await video.play();s.getTracks().forEach(t=>t.onended=stopCamera);$('camera').textContent=$('outputCamera').textContent='カメラをオフ';$('calibrate').disabled=false;status('cameraStatus','顔をカメラへ向けてください。')}catch(e){stopCamera();status('cameraStatus',deviceError(e,'カメラ'),true)}finally{cameraStarting=false}}
$('camera').onclick=$('outputCamera').onclick=toggleCamera;$('showCamera').onchange=()=>video.classList.toggle('visible',$('showCamera').checked);$('calibrate').onclick=()=>status('cameraStatus','正面位置を再設定しました。');
function faceValues(r){const cats=r?.faceBlendshapes?.[0]?.categories;if(!cats)return null;const m=Object.fromEntries(cats.map(c=>[c.categoryName,c.score]));const lm=r.faceLandmarks?.[0];let roll=0,x=0;if(lm){roll=Math.atan2(lm[263].y-lm[33].y,lm[263].x-lm[33].x);x=(.5-lm[1].x)*2}return{mouth:clamp((m.jawOpen||0)*1.8),blink:clamp(((m.eyeBlinkLeft||0)+(m.eyeBlinkRight||0))*.65),smile:clamp(((m.mouthSmileLeft||0)+(m.mouthSmileRight||0))*.75),roll,x}}
function mouthLevel(){if(!analyser||(!micStream&&(audio.paused||audio.ended)))return 0;analyser.getFloatTimeDomainData(samples);let sum=0;for(const v of samples)sum+=v*v;return clamp((Math.sqrt(sum/samples.length)-config.threshold)*Number(config.sensitivity)*8)}
function frame(p){if(config.expression!=='auto')return config.expression;if(p.blink>.55)return'blink';if(p.mouth>.55)return'open';if(p.mouth>.16)return'small';if(p.smile>.35)return'happy';return'neutral'}
function draw(now,target=ctx,transparent=false){const W=target.canvas.width,H=target.canvas.height;target.clearRect(0,0,W,H);if(!transparent&&config.background!=='transparent'){target.fillStyle={green:'#00ff00',dark:'#20222c',white:'#fff'}[config.background];target.fillRect(0,0,W,H)}if(atlas&&model){const sw=atlas.width/3,sh=atlas.height/2,i=model.frames[frame(smooth)]??0;let h=H*.96*config.zoom*(config.framing==='bust'?1.85:1),w=h*(sw/sh),y=config.framing==='bust'?H*.03:H*.98-h;target.save();target.translate(W/2+smooth.x*28,y+h*.3+(config.motion?Math.sin(now/1000)*2.5:0));target.rotate(smooth.roll*.22+(config.motion?Math.sin(now/2600)*.004:0));target.drawImage(atlas,(i%3)*sw,Math.floor(i/3)*sh,sw,sh,-w/2,-h*.3,w,h);target.restore()}if(config.accessory&&pet){const w=W*.23,h=w*pet.height/pet.width,x=config.petPosition==='left'?W*.02:W*.98-w,y=H*.98;target.save();target.translate(x+w/2,y);target.rotate(config.motion?Math.sin(now/1600)*.03:0);target.scale(1,config.motion?1+Math.sin(now/1050)*.015:1);target.drawImage(pet,-w/2,-h,w,h);target.restore()}}
function tick(now){requestAnimationFrame(tick);const dt=Math.min(100,now-last);last=now;let t={mouth:0,blink:0,smile:0,roll:0,x:0};if(camStream&&tracker&&video.readyState>=2&&now-lastDetect>70&&video.currentTime!==lastVideoTime){lastDetect=now;lastVideoTime=video.currentTime;try{face=faceValues(tracker.detectForVideo(video,now))}catch{stopCamera()}}if(face)t={...t,...face};const ml=mouthLevel();if(ml)t.mouth=ml;if(!face&&config.motion){if(now>nextBlink){blinkUntil=now+150;nextBlink=now+2600+Math.random()*2600}t.blink=now<blinkUntil?1:0}if(now<demoUntil){t.mouth=Math.max(0,Math.sin(now/110)*.5+.25);t.smile=.7;t.roll=Math.sin(now/420)*.15}for(const k in smooth){const speed=k==='mouth'?22:k==='blink'?30:8;smooth[k]+=(t[k]-smooth[k])*(1-Math.exp(-dt*speed/1000))}draw(now);$('level').value=ml;$('levelText').value=Math.round(ml*100)+'%';$('state').textContent=now<demoUntil?'動きの見本':micStream||(!audio.paused&&!audio.ended)?'音声に連動中':face?'顔に連動中':'待機中'}
requestAnimationFrame(tick);$('demo').onclick=()=>demoUntil=performance.now()+6000;
$('snapshot').onclick=()=>{if(!atlas)return;const c=document.createElement('canvas');c.width=c.height=1080;draw(performance.now(),c.getContext('2d'),true);c.toBlob(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=config.character+'-'+config.costume+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)},'image/png')};
$('output').onclick=()=>{const u=new URL(location.href);u.search='';u.searchParams.set('output','1');for(const k of settingIds)u.searchParams.set(k,config[k]);window.open(u,'mautuber-output')};
if(outputMode){document.body.classList.add('output-mode');$('outputControls').hidden=false}$('hideControls').onclick=()=>$('outputControls').hidden=true;canvas.ondblclick=()=>{if(outputMode)$('outputControls').hidden=!$('outputControls').hidden};addEventListener('pagehide',()=>{stopMic();stopCamera();audio.pause()});
