'use strict';
const $=id=>document.getElementById(id), canvas=$('avatar'), ctx=canvas.getContext('2d');
const sprite=new Image();sprite.src='avatar.png';let ready=false;sprite.onload=()=>ready=true;sprite.onerror=()=>message('キャラクター画像を読み込めませんでした。ページを再読み込みしてください。',true);
let ac,analyser,micSource,fileSource,stream,bins,mode='mic',requestId=0,demoUntil=0,smooth=0,lastVoice=0,blinkAt=performance.now()+2200,blinkUntil=0,objectUrl;
const audio=$('audio');
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error)}
async function context(){if(!ac){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error('AudioContext');ac=new AudioContext();analyser=ac.createAnalyser();analyser.fftSize=1024;bins=new Float32Array(analyser.fftSize)}if(ac.state==='suspended')await ac.resume()}
function stopMic(){requestId++;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(micSource){micSource.disconnect();micSource=null}$('mic').textContent='マイクをオン';$('mic').classList.remove('active');$('mic').disabled=false;smooth=0;lastVoice=0}
function tab(next){stopMic();audio.pause();demoUntil=0;mode=next;for(const name of ['mic','file']){const active=name===next;$(name+'Tab').setAttribute('aria-selected',active);$(name+'Tab').tabIndex=active?0:-1;$(name+'Panel').hidden=!active}message('音声はこのブラウザ内で処理されます。')}
$('micTab').onclick=()=>tab('mic');$('fileTab').onclick=()=>tab('file');for(const name of ['mic','file'])$(name+'Tab').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'mic':e.key==='End'?'file':name==='mic'?'file':'mic';tab(next);$(next+'Tab').focus()}};
$('mic').onclick=async()=>{if(stream){stopMic();return}if(!navigator.mediaDevices?.getUserMedia){message('このブラウザではマイクを使えません。録音音声を選ぶか、別のブラウザで開いてください。',true);return}const id=++requestId;$('mic').disabled=true;message('マイクの許可を待っています…');try{await context();const input=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(id!==requestId||mode!=='mic'){input.getTracks().forEach(t=>t.stop());return}stream=input;micSource=ac.createMediaStreamSource(stream);micSource.connect(analyser);stream.getAudioTracks()[0].onended=()=>{stopMic();message('マイクが切断されました。再度オンにしてください。',true)};$('mic').textContent='マイクをオフ';$('mic').classList.add('active');message('聞いています。声を出すと口が動きます。')}catch(e){message(e.name==='NotAllowedError'?'マイクが許可されていません。ブラウザのサイト設定で許可するか、録音音声をお試しください。':e.name==='NotFoundError'?'マイクが見つかりません。接続を確認してください。':'マイクを開始できませんでした。接続や他のアプリでの使用状況を確認してください。',true)}finally{if(id===requestId)$('mic').disabled=false}};
$('file').onchange=()=>{const file=$('file').files[0];if(!file)return;audio.pause();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);audio.src=objectUrl;$('filename').textContent=file.name;audio.load();message('再生ボタンを押すと、音声に合わせて動きます。')};
audio.onplay=async()=>{stopMic();demoUntil=0;try{await context();if(!fileSource){fileSource=ac.createMediaElementSource(audio);fileSource.connect(analyser);fileSource.connect(ac.destination)}message('音声を再生しています。')}catch(e){audio.pause();message('音声解析を開始できませんでした。ページを再読み込みしてお試しください。',true)}};
audio.onpause=()=>{smooth=0;lastVoice=0};audio.onended=()=>{smooth=0;lastVoice=0;message('再生が終わりました。もう一度再生できます。')};audio.onerror=()=>message('この音声形式を再生できません。MP3やWAVでお試しください。',true);
$('sensitivity').oninput=()=>{$('sensitivityValue').value=Number($('sensitivity').value).toFixed(1)+'×'};
$('motion').checked=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;
$('demo').onclick=()=>{stopMic();audio.pause();demoUntil=performance.now()+6000;message('6秒間の動きの見本です。音声は流れません。')};
function frame(now){let level=0;const demo=now<demoUntil;const active=Boolean(stream)||(mode==='file'&&!audio.paused&&!audio.ended);if(analyser&&active){analyser.getFloatTimeDomainData(bins);let sum=0;for(const x of bins)sum+=x*x;level=Math.min(1,Math.sqrt(sum/bins.length)*Number($('sensitivity').value)*6)}if(demo)level=Math.max(0,Math.sin(now/115)*.45+.2);smooth+=(level-smooth)*(level>smooth?.7:.3);if(smooth>.085)lastVoice=now;const speaking=(active||demo)&&now-lastVoice<90&&lastVoice>0;$('level').value=smooth;$('levelText').textContent=Math.round(smooth*100)+'%';$('state').textContent=demo?'動きの見本':speaking?'話しています':stream?'マイク入力中':active?'音声再生中':'待機中';$('caption').textContent=speaking?'うん、聞こえてる。':'声を聞かせて。';const move=$('motion').checked;if(now>blinkAt){blinkUntil=now+140;blinkAt=now+2600+Math.random()*2700}const blink=move&&now<blinkUntil;if(ready){ctx.fillStyle='white';ctx.fillRect(0,0,800,800);ctx.save();const bob=move?Math.sin(now/1050)*2.5+smooth*4:0;ctx.translate(400,790-bob);ctx.rotate(move?Math.sin(now/2200)*.004:0);const scale=800/627;ctx.scale(scale,scale);ctx.translate(-313.5,-619);ctx.drawImage(sprite,0,0,627,627,0,0,627,627);if(blink)ctx.drawImage(sprite,220,627+153,190,53,220,153,190,53);if(speaking)ctx.drawImage(sprite,627+296,211,35,33,296,211,35,33);ctx.restore()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.addEventListener('pagehide',()=>{stopMic();audio.pause();if(objectUrl)URL.revokeObjectURL(objectUrl);ac?.close()});
